# Generated by Django 5.1.4 on 2025-01-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productscart_productsitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsitem',
            old_name='save_post',
            new_name='user',
        ),
    ]
