# Generated by Django 5.1.4 on 2025-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_save_post_productsitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
