# Generated by Django 5.1.4 on 2025-01-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_combo_user_alter_combo_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='client',
            new_name='user',
        ),
    ]
