# Generated by Django 5.1.4 on 2025-01-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_courierreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
